AllCops:
  NewCops: enable
  Exclude:
    - 'bin/webpack'
    - 'bin/webpack-dev-server'
    - 'bin/yarn'
    - 'bin/bundle'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'config/spring.rb'

Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'
    - 'spec/**/*'
    - "config/environments/development.rb"

Style/GlobalStdStream:
  Exclude:
    - 'config/environments/production.rb'

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Style/RedundantFetchBlock:
  Exclude:
    - 'config/puma.rb'

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Security/MarshalLoad:
  Exclude:
    - 'app/controllers/api_controller.rb'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RedundantInterpolation:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Style/NegatedWhile:
  Enabled: false

Style/RedundantParentheses:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/SymbolArray:
  EnforcedStyle: brackets

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
  Exclude:
    - 'config/environments/development.rb'
    - 'config/environments/test.rb'
    - 'db/seeds.rb'


Lint/EmptyClass:
  Exclude:
    - "app/services/base.rb"
    - "lib/api/base.rb"